#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
container="agrorumo-global-deletion-${RANDOM}-$$"

cleanup() {
  # This name is generated by this test and can never target a project
  # container. Force-removal is limited to that disposable fixture.
  docker rm -f "$container" >/dev/null 2>&1 || true
}
trap cleanup EXIT

docker run -d --name "$container" \
  -e POSTGRES_PASSWORD=postgres \
  postgres:17.10-bookworm >/dev/null

for _attempt in $(seq 1 60); do
  if docker exec "$container" pg_isready -U postgres >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
docker exec "$container" pg_isready -U postgres >/dev/null

docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
CREATE SCHEMA auth;
CREATE SCHEMA extensions;
CREATE SCHEMA vault;
CREATE EXTENSION pgcrypto WITH SCHEMA extensions;

-- PostgreSQL's stock image does not ship Supabase Vault. This disposable
-- fixture models its API; production preflight requires the real encrypted
-- vault extension and never uses this test-only plaintext implementation.
CREATE TABLE vault.secrets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  secret text NOT NULL,
  name text,
  description text
);
CREATE VIEW vault.decrypted_secrets AS
SELECT id, secret AS decrypted_secret FROM vault.secrets;
CREATE FUNCTION vault.create_secret(
  new_secret text,
  new_name text DEFAULT NULL,
  new_description text DEFAULT '',
  new_key_id uuid DEFAULT NULL
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_id uuid;
BEGIN
  INSERT INTO vault.secrets (secret, name, description)
  VALUES (new_secret, new_name, new_description)
  RETURNING id INTO v_id;
  RETURN v_id;
END
$$;

CREATE TABLE auth.users (
  id uuid PRIMARY KEY,
  email text,
  raw_user_meta_data jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE auth.identities (
  id text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider text NOT NULL
);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
CREATE TABLE public.pragas_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text
);
CREATE TABLE public.subscriptions (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan text NOT NULL DEFAULT 'free',
  app text NOT NULL,
  status text NOT NULL,
  provider text NOT NULL DEFAULT 'free',
  PRIMARY KEY (user_id, app)
);
CREATE TABLE public.pragas_app_links (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  link_version text NOT NULL,
  active boolean NOT NULL,
  linked_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  last_linked_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  deactivated_at timestamptz
);
CREATE TABLE public.pragas_deletion_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  status text NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  last_error_code text,
  next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  requested_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  app_cleanup_completed_at timestamptz,
  reactivated_at timestamptz,
  reactivation_request_id uuid,
  reactivation_idempotency_key uuid,
  lease_token uuid,
  lease_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE public.pragas_push_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  is_active boolean NOT NULL,
  notifications_enabled boolean NOT NULL,
  revoked_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE public.pragas_notification_queue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);
CREATE TABLE public.pragas_ai_idempotency_records (
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scope text NOT NULL,
  idempotency_key uuid NOT NULL,
  request_hash text NOT NULL,
  state text NOT NULL DEFAULT 'processing',
  lease_token uuid,
  lease_expires_at timestamptz,
  provider_started_at timestamptz,
  unknown_outcome_at timestamptz,
  response_status integer,
  response_body jsonb,
  started_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  completed_at timestamptz,
  response_expires_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (user_id, scope, idempotency_key)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pragas_ai_idempotency_records TO service_role;
CREATE TABLE public.analytics_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- production analytics_events.user_id is nullable; mirror it so the
  -- null-subject fail-open path is exercised against the real shape
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  app text NOT NULL,
  pragas_event_id uuid,
  event text NOT NULL,
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  platform text NOT NULL,
  timestamp timestamptz NOT NULL
);
CREATE UNIQUE INDEX analytics_events_pragas_event_unique
  ON public.analytics_events (user_id, pragas_event_id)
  WHERE app = 'rumo-pragas' AND pragas_event_id IS NOT NULL;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analytics_events TO service_role;
CREATE FUNCTION public.reserve_pragas_ai_idempotency(
  p_user_id uuid, p_scope text, p_idempotency_key uuid, p_request_hash text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_lease uuid := gen_random_uuid();
BEGIN
  INSERT INTO public.pragas_ai_idempotency_records (
    user_id, scope, idempotency_key, request_hash, state,
    lease_token, lease_expires_at
  ) VALUES (
    p_user_id, p_scope, p_idempotency_key, p_request_hash, 'processing',
    v_lease, clock_timestamp() + interval '5 minutes'
  );
  RETURN jsonb_build_object('state', 'reserved', 'lease_token', v_lease);
END
$$;
GRANT EXECUTE ON FUNCTION public.reserve_pragas_ai_idempotency(uuid, text, uuid, text)
  TO service_role;
CREATE FUNCTION public.record_pragas_analytics_events(p_user_id uuid, p_events jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  INSERT INTO public.analytics_events (
    user_id, app, pragas_event_id, event, properties, platform, timestamp
  ) VALUES (
    p_user_id, 'rumo-pragas', (p_events -> 0 ->> 'event_id')::uuid,
    p_events -> 0 ->> 'event', '{}'::jsonb, 'ios', clock_timestamp()
  );
  RETURN jsonb_build_object('inserted', 1);
END
$$;
GRANT EXECUTE ON FUNCTION public.record_pragas_analytics_events(uuid, jsonb)
  TO service_role;
SQL

docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres \
  < "$repo_root/supabase/migrations/20260715173000_agrorumo_global_account_deletion_requests.sql"

docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
INSERT INTO auth.users (id, email)
VALUES
  ('11111111-1111-4111-8111-111111111111', 'private@example.test'),
  ('10101010-1010-4010-8010-101010101010', 'operator@example.test');
INSERT INTO public.pragas_app_links (user_id, link_version, active)
VALUES ('11111111-1111-4111-8111-111111111111', '2026-07-14.1', true);
INSERT INTO public.pragas_push_tokens (user_id, is_active, notifications_enabled)
VALUES ('11111111-1111-4111-8111-111111111111', true, true);
INSERT INTO public.pragas_notification_queue (owner_user_id)
VALUES ('11111111-1111-4111-8111-111111111111');

SELECT public.begin_agrorumo_account_deletion_challenge(
  '11111111-1111-4111-8111-111111111111',
  '22222222-2222-4222-8222-222222222222',
  '33333333-3333-4333-8333-333333333333',
  repeat('a', 64),
  'agrorumo-global-account-deletion/2026-07-16.1'
);

DO $$
DECLARE
  v_challenge_created_at timestamptz;
  v_reauthentication_not_before_at timestamptz;
BEGIN
  BEGIN
    PERFORM public.reserve_agrorumo_account_deletion_request(
      '11111111-1111-4111-8111-111111111111',
      '22222222-2222-4222-8222-222222222222',
      clock_timestamp(),
      clock_timestamp(),
      '33333333-3333-4333-8333-333333333333',
      repeat('a', 64),
      'agrorumo-global-account-deletion/2026-07-16.1',
      'password',
      false,
      NULL,
      '44444444-4444-4444-8444-444444444444',
      '55555555-5555-4555-8555-555555555555'
    );
    RAISE EXCEPTION 'same_session_reauthentication_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'fresh_reauthentication_required' THEN RAISE; END IF;
  END;
  SELECT created_at INTO v_challenge_created_at
    FROM public.agrorumo_account_deletion_challenges
   WHERE id = '33333333-3333-4333-8333-333333333333';
  SELECT reauthentication_not_before_at INTO v_reauthentication_not_before_at
    FROM public.agrorumo_account_deletion_challenges
   WHERE id = '33333333-3333-4333-8333-333333333333';
  BEGIN
    PERFORM public.reserve_agrorumo_account_deletion_request(
      '11111111-1111-4111-8111-111111111111',
      '66666666-6666-4666-8666-666666666666',
      clock_timestamp(),
      v_challenge_created_at - interval '1 minute',
      '33333333-3333-4333-8333-333333333333',
      repeat('a', 64),
      'agrorumo-global-account-deletion/2026-07-16.1',
      'password',
      false,
      NULL,
      '44444444-4444-4444-8444-444444444444',
      '55555555-5555-4555-8555-555555555555'
    );
    RAISE EXCEPTION 'pre_challenge_amr_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'fresh_reauthentication_required' THEN RAISE; END IF;
  END;
  BEGIN
    PERFORM public.reserve_agrorumo_account_deletion_request(
      '11111111-1111-4111-8111-111111111111',
      '66666666-6666-4666-8666-666666666666',
      date_trunc('second', v_challenge_created_at),
      date_trunc('second', v_challenge_created_at),
      '33333333-3333-4333-8333-333333333333',
      repeat('a', 64),
      'agrorumo-global-account-deletion/2026-07-16.1',
      'password',
      false,
      NULL,
      '44444444-4444-4444-8444-444444444444',
      '55555555-5555-4555-8555-555555555555'
    );
    RAISE EXCEPTION 'same_second_pre_challenge_amr_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'fresh_reauthentication_required' THEN RAISE; END IF;
  END;
  IF v_reauthentication_not_before_at
     <> date_trunc('second', v_challenge_created_at) + interval '1 second'
  THEN
    RAISE EXCEPTION 'strict_reauthentication_boundary_is_not_next_second';
  END IF;
END
$$;

CREATE TEMP TABLE first_result AS
SELECT public.reserve_agrorumo_account_deletion_request(
  '11111111-1111-4111-8111-111111111111',
  '66666666-6666-4666-8666-666666666666',
  (SELECT reauthentication_not_before_at
     FROM public.agrorumo_account_deletion_challenges
    WHERE id = '33333333-3333-4333-8333-333333333333'),
  (SELECT reauthentication_not_before_at
     FROM public.agrorumo_account_deletion_challenges
    WHERE id = '33333333-3333-4333-8333-333333333333'),
  '33333333-3333-4333-8333-333333333333',
  repeat('a', 64),
  'agrorumo-global-account-deletion/2026-07-16.1',
  'password',
  false,
  NULL,
  '44444444-4444-4444-8444-444444444444',
  '55555555-5555-4555-8555-555555555555'
) AS value;

CREATE TEMP TABLE replay_result AS
SELECT public.reserve_agrorumo_account_deletion_request(
  '11111111-1111-4111-8111-111111111111',
  '66666666-6666-4666-8666-666666666666',
  clock_timestamp(),
  clock_timestamp(),
  '33333333-3333-4333-8333-333333333333',
  repeat('a', 64),
  'agrorumo-global-account-deletion/2026-07-16.1',
  'password',
  false,
  NULL,
  '44444444-4444-4444-8444-444444444444',
  '77777777-7777-4777-8777-777777777777'
) AS value;

DO $$
DECLARE
  v_request_id uuid;
  v_link jsonb;
BEGIN
  IF (SELECT value ->> 'state' FROM first_result) <> 'requested' THEN
    RAISE EXCEPTION 'first_request_not_created';
  END IF;
  IF (SELECT value ->> 'state' FROM replay_result) <> 'already_requested'
     OR (SELECT value ->> 'receipt_id' FROM replay_result)
        <> '55555555-5555-4555-8555-555555555555'
  THEN
    RAISE EXCEPTION 'idempotent_replay_did_not_recover_original_receipt';
  END IF;
  IF EXISTS (SELECT 1 FROM public.pragas_app_links WHERE active) THEN
    RAISE EXCEPTION 'pragas_access_not_suspended';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.pragas_push_tokens
     WHERE is_active OR notifications_enabled OR revoked_at IS NULL
  ) THEN
    RAISE EXCEPTION 'pragas_push_not_revoked';
  END IF;
  IF EXISTS (SELECT 1 FROM public.pragas_notification_queue) THEN
    RAISE EXCEPTION 'queued_push_not_removed';
  END IF;
  IF EXISTS (SELECT 1 FROM public.agrorumo_account_deletion_challenges) THEN
    RAISE EXCEPTION 'consumed_challenge_was_retained';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.pragas_deletion_jobs
     WHERE user_id = '11111111-1111-4111-8111-111111111111'
       AND status = 'requested'
  ) THEN
    RAISE EXCEPTION 'app_cleanup_not_queued';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.agrorumo_account_deletion_requests
     WHERE subject_ref LIKE '%11111111%'
  ) OR EXISTS (
    SELECT 1 FROM public.agrorumo_account_deletion_challenges
     WHERE subject_ref LIKE '%11111111%'
  ) THEN
    RAISE EXCEPTION 'raw_user_uuid_persisted_in_subject_reference';
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name LIKE 'agrorumo_account_deletion%'
       AND column_name IN ('email', 'phone', 'name', 'user_id')
  ) THEN
    RAISE EXCEPTION 'raw_pii_column_added_to_queue';
  END IF;
  IF public.resolve_agrorumo_account_deletion_subject(
    (SELECT id FROM public.agrorumo_account_deletion_requests)
  ) IS DISTINCT FROM '11111111-1111-4111-8111-111111111111'::uuid THEN
    RAISE EXCEPTION 'service_subject_resolution_failed';
  END IF;
  IF public.get_agrorumo_account_deletion_status(
    '55555555-5555-4555-8555-555555555555'
  ) ->> 'status' <> 'requested_manual_review' THEN
    RAISE EXCEPTION 'receipt_status_lookup_failed';
  END IF;
  IF public.get_agrorumo_account_deletion_app_gate(
    '11111111-1111-4111-8111-111111111111'
  ) ->> 'found' <> 'true' THEN
    RAISE EXCEPTION 'global_deletion_app_gate_missing';
  END IF;
  PERFORM set_config(
    'request.jwt.claim.sub',
    '11111111-1111-4111-8111-111111111111',
    true
  );
  v_link := public.pragas_link_account();
  IF v_link ->> 'code' <> 'global_deletion_pending'
     OR v_link ->> 'linked' <> 'false'
  THEN
    RAISE EXCEPTION 'global_queue_did_not_precede_pre_cleanup_reactivation_gate';
  END IF;
  UPDATE public.pragas_deletion_jobs
     SET status = 'blocked_global_decision',
         app_cleanup_completed_at = clock_timestamp()
   WHERE user_id = '11111111-1111-4111-8111-111111111111';
  DELETE FROM public.pragas_profiles
   WHERE user_id = '11111111-1111-4111-8111-111111111111';
  DELETE FROM public.subscriptions
   WHERE user_id = '11111111-1111-4111-8111-111111111111'
     AND app = 'rumo-pragas';
  v_link := public.pragas_link_account();
  IF v_link ->> 'code' <> 'global_deletion_pending'
     OR v_link ->> 'linked' <> 'false'
     OR public.get_agrorumo_account_deletion_app_gate(
          '11111111-1111-4111-8111-111111111111'
        ) ->> 'found' <> 'true'
  THEN
    RAISE EXCEPTION 'global_queue_lost_precedence_after_app_cleanup';
  END IF;
  IF public.get_agrorumo_account_deletion_replay(
    '11111111-1111-4111-8111-111111111111',
    '44444444-4444-4444-8444-444444444444'
  ) ->> 'receipt_id' <> '55555555-5555-4555-8555-555555555555' THEN
    RAISE EXCEPTION 'pre_provider_replay_lookup_failed';
  END IF;
  IF (SELECT count(*) FROM public.list_agrorumo_account_deletion_queue(NULL, 100)) <> 1 THEN
    RAISE EXCEPTION 'manual_queue_listing_failed';
  END IF;

  v_request_id := (SELECT id FROM public.agrorumo_account_deletion_requests);
  PERFORM public.transition_agrorumo_account_deletion_request(
    v_request_id, 'requested_manual_review', 'in_review', 'operator_review_started',
    '10101010-1010-4010-8010-101010101010'
  );
  PERFORM public.transition_agrorumo_account_deletion_request(
    v_request_id, 'in_review', 'processing', 'portfolio_owners_notified',
    '10101010-1010-4010-8010-101010101010'
  );
  BEGIN
    PERFORM public.transition_agrorumo_account_deletion_request(
      v_request_id, 'processing', 'completed', 'missing_evidence',
      '10101010-1010-4010-8010-101010101010'
    );
    RAISE EXCEPTION 'completion_without_evidence_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_deletion_completion_evidence_required' THEN RAISE; END IF;
  END;
  UPDATE public.agrorumo_account_deletion_apple_revocations
     SET state = 'retry_pending', updated_at = clock_timestamp()
   WHERE request_id = v_request_id;
  BEGIN
    PERFORM public.transition_agrorumo_account_deletion_request(
      v_request_id, 'processing', 'completed',
      'coordinated_erasure_evidence_verified',
      '10101010-1010-4010-8010-101010101010',
      'completed', NULL, repeat('e', 64)
    );
    RAISE EXCEPTION 'completion_before_apple_revocation_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_deletion_apple_revocation_incomplete' THEN RAISE; END IF;
  END;
  UPDATE public.agrorumo_account_deletion_apple_revocations
     SET state = 'not_required', updated_at = clock_timestamp()
   WHERE request_id = v_request_id;
  UPDATE public.pragas_deletion_jobs
     SET status = 'requested', app_cleanup_completed_at = NULL
   WHERE user_id = '11111111-1111-4111-8111-111111111111';
  BEGIN
    PERFORM public.transition_agrorumo_account_deletion_request(
      v_request_id, 'processing', 'completed',
      'coordinated_erasure_evidence_verified',
      '10101010-1010-4010-8010-101010101010',
      'completed', NULL, repeat('e', 64)
    );
    RAISE EXCEPTION 'completion_before_app_cleanup_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_deletion_app_cleanup_not_completed' THEN RAISE; END IF;
  END;
  UPDATE public.pragas_deletion_jobs
     SET status = 'blocked_global_decision',
         app_cleanup_completed_at = clock_timestamp()
   WHERE user_id = '11111111-1111-4111-8111-111111111111';
  PERFORM public.transition_agrorumo_account_deletion_request(
    v_request_id,
    'processing',
    'legal_retention_only',
    'statutory_records_scoped',
    '10101010-1010-4010-8010-101010101010',
    'completed',
    'statutory_financial_retention'
  );
  PERFORM public.transition_agrorumo_account_deletion_request(
    v_request_id,
    'legal_retention_only',
    'completed',
    'coordinated_erasure_evidence_verified',
    '10101010-1010-4010-8010-101010101010',
    'completed',
    'statutory_financial_retention',
    repeat('e', 64)
  );
  IF (SELECT count(*) FROM public.agrorumo_account_deletion_events) <> 7 THEN
    RAISE EXCEPTION 'audit_event_count_mismatch';
  END IF;
  IF NOT EXISTS (
    SELECT 1
      FROM public.agrorumo_account_deletion_events
     WHERE request_id = v_request_id
       AND event_type = 'manual_evidence_recorded'
       AND operator_ref ~ '^[0-9a-f]{64}$'
       AND evidence_digest = repeat('e', 64)
  ) OR EXISTS (
    SELECT 1
      FROM public.agrorumo_account_deletion_events
     WHERE operator_ref LIKE '%10101010%'
  ) THEN
    RAISE EXCEPTION 'pseudonymous_operator_evidence_audit_missing';
  END IF;
  BEGIN
    UPDATE public.agrorumo_account_deletion_events SET detail_code = 'tampered';
    RAISE EXCEPTION 'audit_event_mutation_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'agrorumo_deletion_event_immutable' THEN RAISE; END IF;
  END;
  BEGIN
    INSERT INTO public.pragas_app_links (user_id, link_version, active)
    VALUES ('11111111-1111-4111-8111-111111111111', '2026-07-14.1', true)
    ON CONFLICT (user_id) DO UPDATE SET active = true, deactivated_at = NULL;
    RAISE EXCEPTION 'pragas_reactivation_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
END
$$;

SET ROLE service_role;
DO $$
BEGIN
  BEGIN
    INSERT INTO public.pragas_ai_idempotency_records (
      user_id, scope, idempotency_key, request_hash, state,
      lease_token, lease_expires_at
    ) VALUES (
      '11111111-1111-4111-8111-111111111111', 'diagnosis',
      '12121212-1212-4212-8212-121212121212', repeat('a', 64), 'processing',
      '13131313-1313-4313-8313-131313131313', clock_timestamp() + interval '5 minutes'
    );
    RAISE EXCEPTION 'service_role_ai_late_write_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  BEGIN
    INSERT INTO public.analytics_events (
      user_id, app, pragas_event_id, event, properties, platform, timestamp
    ) VALUES (
      '11111111-1111-4111-8111-111111111111', 'rumo-pragas',
      '14141414-1414-4414-8414-141414141414', 'late.write', '{}'::jsonb,
      'ios', clock_timestamp()
    );
    RAISE EXCEPTION 'service_role_analytics_late_write_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  BEGIN
    PERFORM public.reserve_pragas_ai_idempotency(
      '11111111-1111-4111-8111-111111111111', 'chat',
      '15151515-1515-4515-8515-151515151515', repeat('b', 64)
    );
    RAISE EXCEPTION 'security_definer_ai_late_write_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  BEGIN
    PERFORM public.record_pragas_analytics_events(
      '11111111-1111-4111-8111-111111111111',
      jsonb_build_array(jsonb_build_object(
        'event_id', '16161616-1616-4616-8616-161616161616',
        'event', 'late.rpc.write'
      ))
    );
    RAISE EXCEPTION 'security_definer_analytics_late_write_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  -- A NULL-subject row is unattributable to any account under deletion and
  -- must fail open even while a deletion request exists for another user.
  INSERT INTO public.analytics_events (
    user_id, app, pragas_event_id, event, properties, platform, timestamp
  ) VALUES (
    NULL, 'rumo-pragas',
    '17171717-1717-4717-8717-171717171717', 'late.null.subject', '{}'::jsonb,
    'ios', clock_timestamp()
  );
  IF NOT EXISTS (
    SELECT 1
      FROM public.analytics_events
     WHERE pragas_event_id = '17171717-1717-4717-8717-171717171717'
  ) THEN
    RAISE EXCEPTION 'null_subject_analytics_write_was_blocked';
  END IF;
END
$$;
RESET ROLE;

DO $$
BEGIN
  IF has_table_privilege('authenticated', 'public.agrorumo_account_deletion_requests', 'SELECT')
     OR has_table_privilege('authenticated', 'public.agrorumo_account_deletion_challenges', 'SELECT')
     OR has_table_privilege(
       'authenticated',
       'public.agrorumo_account_deletion_apple_revocations',
       'SELECT'
     )
     OR has_table_privilege('authenticated', 'public.agrorumo_deletion_identity_keys', 'SELECT')
  THEN
    RAISE EXCEPTION 'authenticated_role_can_read_private_deletion_queue';
  END IF;
  IF has_table_privilege('service_role', 'public.agrorumo_account_deletion_requests', 'UPDATE')
     OR has_table_privilege(
       'service_role',
       'public.agrorumo_account_deletion_apple_revocations',
       'UPDATE'
     )
     OR has_table_privilege('service_role', 'public.agrorumo_account_deletion_events', 'INSERT')
  THEN
    RAISE EXCEPTION 'service_role_can_bypass_audited_deletion_rpcs';
  END IF;
END
$$;

DO $$
DECLARE
  v_result jsonb;
  v_attempt integer;
BEGIN
  FOR v_attempt IN 1..30 LOOP
    v_result := public.consume_agrorumo_deletion_status_rate_limit('203.0.113.10', 30, 60);
    IF v_result ->> 'allowed' <> 'true' THEN
      RAISE EXCEPTION 'status_rate_limit_rejected_early';
    END IF;
  END LOOP;
  v_result := public.consume_agrorumo_deletion_status_rate_limit('203.0.113.10', 30, 60);
  IF v_result ->> 'allowed' <> 'false' THEN
    RAISE EXCEPTION 'status_rate_limit_failed_open';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.agrorumo_deletion_status_rate_limits
     WHERE actor_ref LIKE '%203.0.113.10%'
  ) THEN
    RAISE EXCEPTION 'raw_status_actor_was_persisted';
  END IF;
END
$$;
SQL

# Adversarial two-session race: confirmation must serialize against both a
# relink and a new active push token. The confirm transaction deliberately
# remains open after its writes so the competing transaction reaches triggers
# while the global request is still uncommitted.
docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
INSERT INTO auth.users (id, email)
VALUES ('88888888-8888-4888-8888-888888888888', 'race@example.test');
INSERT INTO auth.identities (id, user_id, provider)
VALUES ('apple-race-subject', '88888888-8888-4888-8888-888888888888', 'apple');
INSERT INTO public.pragas_app_links (user_id, link_version, active)
VALUES ('88888888-8888-4888-8888-888888888888', '2026-07-14.1', true);
INSERT INTO public.pragas_profiles (user_id, full_name)
VALUES ('88888888-8888-4888-8888-888888888888', 'Before deletion');
INSERT INTO public.pragas_push_tokens (user_id, is_active, notifications_enabled)
VALUES ('88888888-8888-4888-8888-888888888888', true, true);
SELECT public.begin_agrorumo_account_deletion_challenge(
  '88888888-8888-4888-8888-888888888888',
  '99999999-9999-4999-8999-999999999999',
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  repeat('b', 64),
  'agrorumo-global-account-deletion/2026-07-16.1'
);
SQL

(
  docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
BEGIN;
SELECT public.reserve_agrorumo_account_deletion_request(
  '88888888-8888-4888-8888-888888888888',
  'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
  (SELECT reauthentication_not_before_at
     FROM public.agrorumo_account_deletion_challenges
    WHERE id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  (SELECT reauthentication_not_before_at
     FROM public.agrorumo_account_deletion_challenges
    WHERE id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  repeat('b', 64),
  'agrorumo-global-account-deletion/2026-07-16.1',
  'password',
  true,
  repeat('c', 64),
  'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
  'dddddddd-dddd-4ddd-8ddd-dddddddddddd'
);
SELECT pg_sleep(4);
COMMIT;
SQL
) &
confirm_pid=$!
sleep 1
docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
DO $$
BEGIN
  BEGIN
    INSERT INTO public.pragas_app_links (user_id, link_version, active)
    VALUES ('88888888-8888-4888-8888-888888888888', '2026-07-14.1', true)
    ON CONFLICT (user_id) DO UPDATE SET active = true, deactivated_at = NULL;
    RAISE EXCEPTION 'concurrent_relink_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  BEGIN
    INSERT INTO public.pragas_push_tokens (user_id, is_active, notifications_enabled)
    VALUES ('88888888-8888-4888-8888-888888888888', true, true);
    RAISE EXCEPTION 'concurrent_push_enable_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
  BEGIN
    UPDATE public.pragas_profiles
       SET full_name = 'Mutated after deletion'
     WHERE user_id = '88888888-8888-4888-8888-888888888888';
    RAISE EXCEPTION 'concurrent_profile_mutation_was_accepted';
  EXCEPTION WHEN OTHERS THEN
    IF SQLERRM <> 'global_account_deletion_requested' THEN RAISE; END IF;
  END;
END
$$;
SQL
wait "$confirm_pid"

race_result="$(docker exec -i "$container" psql -qAt -v ON_ERROR_STOP=1 -U postgres <<'SQL'
SELECT concat(
  'request=', (SELECT count(*) FROM public.agrorumo_account_deletion_requests
    WHERE receipt_id = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd'),
  ' active_link=', (SELECT count(*) FROM public.pragas_app_links
    WHERE user_id = '88888888-8888-4888-8888-888888888888' AND active),
  ' active_push=', (SELECT count(*) FROM public.pragas_push_tokens
    WHERE user_id = '88888888-8888-4888-8888-888888888888'
      AND (is_active OR notifications_enabled)),
  ' mutated_profile=', (SELECT count(*) FROM public.pragas_profiles
    WHERE user_id = '88888888-8888-4888-8888-888888888888'
      AND full_name <> 'Before deletion')
);
SQL
)"
if [[ "$race_result" != "request=1 active_link=0 active_push=0 mutated_profile=0" ]]; then
  echo "global deletion race invariant failed: $race_result" >&2
  exit 1
fi
echo "global deletion race: $race_result"

docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres <<'SQL'
DO $$
DECLARE
  v_attempt jsonb;
  v_attempt_token uuid;
  v_claimed_token text;
  v_result jsonb;
BEGIN
  v_attempt := public.begin_agrorumo_apple_revocation_attempt(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    repeat('c', 64)
  );
  IF v_attempt ->> 'action' <> 'exchange_code' THEN
    RAISE EXCEPTION 'apple_exchange_was_not_resumed_from_durable_reservation';
  END IF;
  v_attempt_token := (v_attempt ->> 'attempt_token')::uuid;
  PERFORM public.store_agrorumo_apple_revocation_token(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    v_attempt_token,
    repeat('c', 64),
    'fixture-refresh-token-never-in-application-table'
  );
  v_attempt := public.begin_agrorumo_apple_revocation_attempt(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    NULL
  );
  IF v_attempt ->> 'action' <> 'revoke_token' THEN
    RAISE EXCEPTION 'vault_token_was_not_scheduled_for_revocation';
  END IF;
  v_attempt_token := (v_attempt ->> 'attempt_token')::uuid;
  v_claimed_token := public.claim_agrorumo_apple_revocation_token(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    v_attempt_token
  );
  IF v_claimed_token <> 'fixture-refresh-token-never-in-application-table' THEN
    RAISE EXCEPTION 'vault_token_was_not_recoverable_after_process_boundary';
  END IF;
  -- Simulate a process crash after the token claim. Once its bounded lease
  -- expires, a fresh process must recover the same encrypted token.
  UPDATE public.agrorumo_account_deletion_apple_revocations
     SET lease_expires_at = clock_timestamp() - interval '1 second'
   WHERE request_id = (
     SELECT id FROM public.agrorumo_account_deletion_requests
      WHERE receipt_id = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd'
   );
  v_attempt := public.begin_agrorumo_apple_revocation_attempt(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    NULL
  );
  IF v_attempt ->> 'action' <> 'revoke_token' THEN
    RAISE EXCEPTION 'apple_revocation_restart_did_not_reclaim_expired_lease';
  END IF;
  v_attempt_token := (v_attempt ->> 'attempt_token')::uuid;
  IF public.claim_agrorumo_apple_revocation_token(
       '88888888-8888-4888-8888-888888888888',
       'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
       v_attempt_token
     ) IS NULL
  THEN
    RAISE EXCEPTION 'apple_revocation_restart_lost_encrypted_token';
  END IF;
  PERFORM public.record_agrorumo_apple_revocation_result(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    v_attempt_token,
    'retry_pending',
    'apple_token_revocation_failed'
  );
  v_attempt := public.begin_agrorumo_apple_revocation_attempt(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    NULL
  );
  IF v_attempt ->> 'action' <> 'revoke_token' THEN
    RAISE EXCEPTION 'apple_revocation_retry_lost_encrypted_token';
  END IF;
  v_attempt_token := (v_attempt ->> 'attempt_token')::uuid;
  IF public.claim_agrorumo_apple_revocation_token(
       '88888888-8888-4888-8888-888888888888',
       'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
       v_attempt_token
     ) IS NULL
  THEN
    RAISE EXCEPTION 'repeatable_apple_revocation_claim_failed';
  END IF;
  v_result := public.record_agrorumo_apple_revocation_result(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    v_attempt_token,
    'revoked',
    'apple_authorization_revoked'
  );
  IF v_result ->> 'apple_authorization_status' <> 'revoked'
     OR EXISTS (SELECT 1 FROM vault.secrets)
     OR NOT EXISTS (
       SELECT 1
         FROM public.agrorumo_account_deletion_apple_revocations
        WHERE state = 'revoked'
          AND token_vault_secret_id IS NULL
          AND revoked_at IS NOT NULL
     )
     OR public.get_agrorumo_account_deletion_replay(
          '88888888-8888-4888-8888-888888888888',
          'cccccccc-cccc-4ccc-8ccc-cccccccccccc'
        ) ->> 'apple_authorization_status' <> 'revoked'
  THEN
    RAISE EXCEPTION 'apple_revocation_finalization_was_not_atomic';
  END IF;
  -- Finalization replay must be a no-op, not a second audit transition.
  v_result := public.record_agrorumo_apple_revocation_result(
    '88888888-8888-4888-8888-888888888888',
    'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
    v_attempt_token,
    'revoked',
    'apple_authorization_revoked'
  );
  IF v_result ->> 'apple_authorization_status' <> 'revoked' THEN
    RAISE EXCEPTION 'apple_revocation_finalization_replay_failed';
  END IF;
  IF EXISTS (
    SELECT 1
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name LIKE 'agrorumo_account_deletion%'
       AND column_name IN (
         'refresh_token', 'authorization_code', 'apple_subject', 'email', 'user_id'
       )
  ) THEN
    RAISE EXCEPTION 'raw_apple_secret_or_pii_column_was_persisted';
  END IF;
END
$$;

INSERT INTO public.agrorumo_account_deletion_challenges (
  id, subject_ref, initial_session_ref, secret_digest, confirmation_version,
  created_at, reauthentication_not_before_at, expires_at
) VALUES (
  'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee', repeat('d', 64), repeat('e', 64),
  repeat('f', 64), 'agrorumo-global-account-deletion/2026-07-16.1',
  clock_timestamp() - interval '20 minutes',
  date_trunc('second', clock_timestamp() - interval '20 minutes') + interval '1 second',
  clock_timestamp() - interval '10 minutes'
);
SELECT public.purge_agrorumo_account_deletion_ephemera(100);
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.agrorumo_account_deletion_challenges
     WHERE id = 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'
  ) THEN
    RAISE EXCEPTION 'expired_challenge_operational_cleanup_failed';
  END IF;
  IF to_regclass('public.idx_agrorumo_account_deletion_challenges_expires') IS NULL THEN
    RAISE EXCEPTION 'challenge_cleanup_index_missing';
  END IF;
END
$$;
SQL

if rollback_output="$(
  docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U postgres \
    < "$repo_root/supabase/rollback/20260715173000_agrorumo_global_account_deletion_requests.down.sql" \
    2>&1
)"; then
  echo "rollback removed a durable global deletion request" >&2
  exit 1
fi
if ! grep -Fq 'global_deletion_rollback_refuses_durable_requests' <<<"$rollback_output"; then
  echo "rollback refusal failed for an unexpected reason" >&2
  printf '%s\n' "$rollback_output" >&2
  exit 1
fi
if [[ "$(docker exec "$container" psql -qAt -v ON_ERROR_STOP=1 -U postgres \
  -c 'SELECT count(*) FROM public.agrorumo_account_deletion_requests')" != "2" ]]; then
  echo "failed rollback damaged the durable deletion queue" >&2
  exit 1
fi

if rg -n "auth\.admin\.deleteUser|DELETE FROM auth\.users" \
  "$repo_root/supabase/migrations/20260715173000_agrorumo_global_account_deletion_requests.sql" \
  "$repo_root/supabase/functions/pragas-global-account-deletion/index.ts"; then
  echo "global deletion request path must never automatically delete auth.users" >&2
  exit 1
fi

echo "agrorumo global account deletion integration: PASS"
