/* eslint-disable @typescript-eslint/no-require-imports */
/* global module, require */

const { withPodfile, withXcodeProject } = require('expo/config-plugins');

const BUNDLE_PHASE = 'Bundle React Native code and images';
const DEBUG_FILES_PHASE = 'Upload Debug Symbols to Sentry';
const PODFILE_PATCH_TAG = '# @generated by withQuotedSentryXcodeScripts';

function readShellScript(phase, phaseName) {
  if (!phase?.shellScript) {
    throw new Error(`iOS build phase not found: ${phaseName}`);
  }

  return JSON.parse(phase.shellScript);
}

function writeShellScript(phase, script) {
  phase.shellScript = JSON.stringify(script);
}

function quoteBundleScripts(script) {
  const disabledUploadGuard = 'if [ "${SENTRY_DISABLE_AUTO_UPLOAD:-}" = "true" ]; then';
  const sentryInvocation = '/bin/sh "$SENTRY_XCODE_SCRIPT" "$REACT_NATIVE_XCODE_SCRIPT"';
  const guardedInvocation = [
    disabledUploadGuard,
    '  /bin/sh "$REACT_NATIVE_XCODE_SCRIPT"',
    'else',
    `  ${sentryInvocation}`,
    'fi',
  ].join('\n');

  if (script.includes(disabledUploadGuard)) {
    return script;
  }

  if (script.includes('SENTRY_XCODE_SCRIPT=') && script.includes(sentryInvocation)) {
    return script.replace(sentryInvocation, guardedInvocation);
  }

  const unsafeLine = script
    .split('\n')
    .find(
      (line) =>
        line.includes('sentry-xcode.sh') &&
        line.includes('react-native-xcode.sh') &&
        line.includes('/bin/sh'),
    );

  if (!unsafeLine) {
    throw new Error('Unable to locate the Sentry-wrapped React Native bundle command');
  }

  const safeCommand = [
    'SENTRY_XCODE_SCRIPT="$("$NODE_BINARY" --print "require(\'path\').dirname(require.resolve(\'@sentry/react-native/package.json\')) + \'/scripts/sentry-xcode.sh\'")"',
    'REACT_NATIVE_XCODE_SCRIPT="$("$NODE_BINARY" --print "require(\'path\').dirname(require.resolve(\'react-native/package.json\')) + \'/scripts/react-native-xcode.sh\'")"',
    guardedInvocation,
  ].join('\n');

  return script.replace(unsafeLine, safeCommand);
}

function quoteDebugFilesScript(script) {
  if (script.includes('SENTRY_DEBUG_FILES_SCRIPT=')) return script;

  const unsafeLine = script
    .split('\n')
    .find((line) => line.includes('sentry-xcode-debug-files.sh') && line.includes('/bin/sh'));

  if (!unsafeLine) {
    throw new Error('Unable to locate the Sentry debug-files command');
  }

  const safeCommand = [
    'SENTRY_DEBUG_FILES_SCRIPT="$("${NODE_BINARY:-node}" --print "require(\'path\').dirname(require.resolve(\'@sentry/react-native/package.json\')) + \'/scripts/sentry-xcode-debug-files.sh\'")"',
    '/bin/sh "$SENTRY_DEBUG_FILES_SCRIPT"',
  ].join('\n');

  return script.replace(unsafeLine, safeCommand);
}

/**
 * Sentry React Native 7.x emits command-substitution paths as unquoted shell
 * arguments. Xcode consequently splits a repository path containing spaces
 * (for example `AgroRumo Projetos`) before either Sentry script can run.
 * Its disabled-upload branch also re-invokes the React Native script through
 * `sh -c`, which loses quoting again. Keep both branches portable until the
 * upstream plugin is upgraded, without patching node_modules or relying on a
 * machine-local path.
 */
module.exports = function withQuotedSentryXcodeScripts(config) {
  const withPathSafePodScripts = withPodfile(config, (mod) => {
    if (mod.modResults.contents.includes(PODFILE_PATCH_TAG)) return mod;

    const anchor = ['      :ccache_enabled => ccache_enabled?(podfile_properties),', '    )'].join(
      '\n',
    );

    if (!mod.modResults.contents.includes(anchor)) {
      throw new Error('Unable to locate react_native_post_install in the generated Podfile');
    }

    const patch = [
      anchor,
      '',
      `    ${PODFILE_PATCH_TAG}`,
      '    path_safe_expo_scripts = {',
      `      '[CP-User] Generate app.config for prebuilt Constants.manifest' => 'PROJECT_ROOT="$PROJECT_DIR/../.." PROJECT_DIR=Pods bash -l "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"',`,
      `      '[CP-User] Generate updates resources for expo-updates' => 'bash -l "$PODS_TARGET_SRCROOT/../scripts/create-updates-resources-ios.sh"',`,
      '    }',
      '',
      '    path_safe_expo_scripts.each do |phase_name, command|',
      '      phase = installer.pods_project.targets',
      '        .flat_map(&:shell_script_build_phases)',
      '        .find { |candidate| candidate.name == phase_name }',
      '      raise "Missing CocoaPods build phase: #{phase_name}" unless phase',
      '',
      '      phase.shell_script = command',
      '    end',
    ].join('\n');

    mod.modResults.contents = mod.modResults.contents.replace(anchor, patch);
    return mod;
  });

  return withXcodeProject(withPathSafePodScripts, (mod) => {
    const project = mod.modResults;

    const bundlePhase = project.pbxItemByComment(BUNDLE_PHASE, 'PBXShellScriptBuildPhase');
    writeShellScript(bundlePhase, quoteBundleScripts(readShellScript(bundlePhase, BUNDLE_PHASE)));

    const debugFilesPhase = project.pbxItemByComment(DEBUG_FILES_PHASE, 'PBXShellScriptBuildPhase');
    writeShellScript(
      debugFilesPhase,
      quoteDebugFilesScript(readShellScript(debugFilesPhase, DEBUG_FILES_PHASE)),
    );

    return mod;
  });
};
